.github/dependabot.yml, .github/workflows/ci.yaml
Now that we are on GitHub, we need our CI pipeline ASAP :rocket:
=> Add CI and dependabot GitHub actions

.github/workflows/ci.yaml
Since we decided to rename to main later
=> hotfix: add master to action trigger

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
When I integrated CodeQL in the repository I noticed that it found problems in our testing directory. To disable it and make it only focus on scanning the package, we have to do the GitHub action manually.
=> Add CodeQL advanced usage

.github/dependabot.yml, .github/workflows/ci.yaml, autosubmit/autosubmit.py, autosubmit/job/job.py, autosubmit/job/job_list.py, autosubmit/platforms/locplatform.py, autosubmit/platforms/platform.py, autosubmit/platforms/wrappers/wrapper_builder.py, test/unit/test_database_regression.py, test/unit/test_log_recovery.py, test/unit/test_run_command_intregation.py
In GitLab by @dbeltrankyl on Dec 9, 2024, 19:10
This fixes: 
* !527 , in line with this merge, now a job can't be put in the UniqueQueue if it has no ID.
* Fixed an issue with failed jobs when chunks are> 3, retrials are> 5, and the job fulfills the 3 retrials. 
The fix consists of adding a copy(job) in the put method. 
I really thought that was what you put in the multiprocess.Queue() is always a copy of your actual instance. However, I saw that it was affecting the jobs in the Queue. 
Since I have to add a copy ( not a deep one, tho, so it shouldn't be expensive), an alternative would be to pass job.id, fail_count, out , err, status, and create a new job in the log_recovery process.
* Reorganized the log retrievals in case of failure 
Now, instead of reconnecting to the platform and not …
=> Fixed DB test # Means to fix the failed jobs not being written in the db due the logs not being retrieved

autosubmit/job/job.py, autosubmit/notifications/mail_notifier.py, docs/source/userguide/configure/index.rst, setup.py, test/unit/test_job_pytest.py
In GitLab by @dbeltrankyl on Dec 10, 2024, 14:55
This adds again the notify_on attribute. 
```yaml
JOB:
NOTIFY_ON:
- RUNNING
- COMPLETED
```
Also the 
```yaml
mail:
to: 
- mail_1
```
expects a yaml_list
#1484 , #1468 
TODO: 
I believe the automail of BSC can't be tested outside the ibsc
=> Draft: re-added notify_on

autosubmit/job/job.py, test/unit/test_job_pytest.py
Discovered in the t-suite week 50 
What happens? 
* Autosubmit 4.1.12 dev crash in local jobs if the job was exiting from an older version
How to reproduce it
* Create a list of jobs with the local platform with 4.1.11 or older. autosubmit create $expid
* Change version, and perform autosubmit run $expid
=> (DEV VERSION ) Fix issue with the wrapper attribute

autosubmit/job/job.py, autosubmit/platforms/platform.py
The fix involves moving the Log.result message to the right place. During the log retrieval process 
What does this fixes:
master branch:
* Run an experiment with a wrapper that fails. 
A result message is displayed similar to:
```
2024-12-17 13:16:34,376 LUMI(log_recovery) Successfully recovered log for job 'a000_20221101_fc0_3_LUMI_SLURM_FAILED' and retry '6'.
```
This branch:
* Run an experiment with a wrapper. 
A result message is displayed similar to:
```
MARENOSTRUM5(log_recovery) Successfully recovered log for job 'a000_20221101_fc0_1_MN5_WRAPPED_FAILED' and retry '0'.
MARENOSTRUM5(log_recovery) Successfully recovered log for job 'a000_20221101_fc0_1_MN5_WRAPPED_FAILED' and retry '1'.
MARENOSTRUM5(log_recovery) Successfully recovered log for job …
```
=> (LOGS) Inner jobs retrial for vertical wrapper are not displayed closes #2039

test/unit/provenance/test_rocrate.py
PR to fix our CI pipeline because `pyyaml` is not installed indirectly anymore by one of our dependencies and is used inside `test_rocrate.py`.
I tried to change it to `ruamel.yaml` by doing:
```diff
diff --git a/test/unit/provenance/test_rocrate.py b/test/unit/provenance/test_rocrate.py
index 8e0b4e1c..134c4190 100644
--- a/test/unit/provenance/test_rocrate.py
+++ b/test/unit/provenance/test_rocrate.py
@@ -6,7 +6,8 @@ from subprocess import CalledProcessError
from tempfile import TemporaryDirectory
from unittest import TestCase
-import yaml
+from io import StringIO
+from ruamel.yaml import YAML
from mock import Mock, patch
from rocrate.rocrate import File
from rocrate.rocrate import ROCrate
@@ -48,7 +49,10 @@ class TestRoCrate(TestCase):
Path(conf_dir, 'metadata').mkdir()
unified_config …
```
=> add pyyaml to test_require

CHANGELOG, autosubmit/job/job.py, test/unit/test_job_pytest.py
Note: this requires https://github.com/BSC-ES/autosubmit-config-parser/pull/59 changes. 
The issue:
I noticed that although the custom_directive is assigned to the variable, it is not assigned in the correct order. 
Some normalization or/and preparation stuff happens while the "custom_directive" is still assigned to a placeholder. Ex. CUSTOM_DIRECTIVE: "%current_something%
So it does nothing. 
Configuration:
https://github.com/BSC-ES/autosubmit-config-parser/pull/59#issuecomment-2575118765
Bug:
https://github.com/BSC-ES/autosubmit-config-parser/pull/59#issuecomment-2575298435
Solution: 
The solution consists in:
Instead of getting the value from job_data, it is now getting from the parameters dict based on CURRENT_ values. With this, we ensure to have the most updated variable, with all …
=> Custom directives added letter by letter

autosubmit/job/job_packages.py, test/unit/test_job_package.py
Closes #2065 
It's pending that I write a test that fails if we ever change it, accidentally, again to `&`.
=> GH-2065: Correct join character for jobs in wrapper (was &, is now _)

autosubmit/job/job.py, test/unit/test_job_pytest.py
This branches fixes a bug related with recovery + log_path when it continues the run with a job_list of a previous version. 
Ready to review
=> Adjust log_path  for existing job_list

docs/source/index.rst, docs/source/moduledoc/index.rst
In GitLab by @LuiggiTenorioK on Nov 26, 2024, 11:03
Related issue: #1454
This should help the API/GUI docs become more relevant for search engines by adding hyperlinks in the home page of the main Autosubmit documentation.
=> Add API/GUI links in the docs home page

autosubmit/platforms/platform.py
While reading logs I got miffed that retrial was used instead of retry.
Fix that in log messages.
The code is still full of variables using retrial and the configuration YAML also contains it.
Related: #2088
=> Change logging mentioning retrial to retry. We are not heading to court

autosubmit/job/job.py, test/unit/test_job_pytest.py
This adds the missing ready_date attribute when swapping AS version from <4.1.12 to 4.1.12*.
Ready to review: @kinow , @isimo00 ( should be fast )
Fyi: @Lerriola
=> Added ready_date when swapping versions

autosubmit/autosubmit.py, autosubmit/platforms/platform.py, test/unit/test_log_recovery.py
This PR is to fix a corner case in which the log_recovery process is dead.
related to #2054
- Added refresh_log_recovery_process
Sets the worker or/and call to spawn a new log_recovery process
- Added log_recovery clean_up
Resets everything as if it were new
=> gh-2054-logs-dead-revival

autosubmit/autosubmit.py, bin/autosubmit, test/unit/test_commands.py
Implements #2083
Outcome example: 
```python
/home/dbeltran/.venv39/bin/python /home/dbeltran/GIT_autosubmit/bin/autosubmit -lc DEBUG create a500 -cw -np -f 
Error in arguments: Namespace(version=False, logfile='DEBUG', logconsole='DEBUG', command='create', expid='a500', noplot=True, hide=False, detail=False, output=None, group_by=None, expand=None, expand_status=None, notransitive=False, check_wrapper=True, update_version=False, profile=False, force=True)
[ERROR] Error in command: create
[ERROR] Error in experiment: a500
Invalid Autosubmit configuration: Experiment a500 does not exist
Traceback (most recent call last):
File "/home/dbeltran/GIT_autosubmit/bin/autosubmit", line 40, in main
return_value = Autosubmit.run_command(args)
File …
```
=> Better traceback

autosubmit/platforms/paramiko_platform.py, docs/source/userguide/configure/index.rst, docs/source/userguide/index.rst, docs/source/userguide/user_mapping.rst, setup.py, test/unit/test_paramiko_platform_pytest.py
In GitLab by @dbeltrankyl on Nov 21, 2024, 16:02
=> Gl 1455 user mapping

log/log.py
While investigating why autosubmit spends a surprising amount of CPU on hammering the LOG_<expid> directory by 
listing files again and again, I stumbled upon log/log.py:
```
max_retrials = 3
retrials = 0
timeout = 5
while not os.path.exists(file_path) and retrials < max_retrials:
sleep(timeout*retrials)
try:
directory, filename = os.path.split(file_path)
if not os.path.exists(directory):
os.mkdir(directory)
files = [f for f in os.listdir(directory) if os.path.isfile
```
The sleep() was hardcoded as 0. 
This PR fixes that to 1 second (*3), while at the same time fixes the 
"retrials" to the correct "retries".
=> Fixed the sleep to actually sleep

autosubmit/autosubmit.py, autosubmit/helpers/utils.py, autosubmit/job/job_list.py, autosubmit/platforms/locplatform.py, pyproject.toml, test/unit/helpers/test_utils.py
I  used [Sciagraph](https://www.sciagraph.com/) to proflie Autosubmit for #2160 and found that that profiler was helpful actually in providing the detailed memory usage of the imports in our code.
To install and configure it, I ran `pip install sciagraph` and then did the account set up at https://account.sciagraph.com/ui/ (for the free version, they have paid plans too).
Sciagraph uses pydantic, which relies on typing_extensions >= 4.12, but we had a fixed range for ==4.9.0. I replaced it by `==4.*` as I think the typing extensions shouldn't break between major/minor updates for us.
Then I launched sciagraph with this command:
```bash
$ autosubmit create -v -f -np...
$ python -m sciagraph run /home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit -lc DEBUG run a00g
```
I let it run a …
=> Import certain packages only when necessary to consume less memory (was 78.7 MB, is now 37.3 MB)

README.md, docs/source/installation/index.rst
At installation time, pip must have version `>=24.0` to correctly install with only the `pyproject.toml` file
Closes #2180
=> Add PIP version requirement

autosubmit/platforms/paramiko_platform.py
This fixes #2102. 
For a month, there has been an issue with marenostrum5 in which the sacct, sbatch, or squeue commands are not found. 
I changed the exception to trigger the recovery platform code instead of stopping Autosubmit when it happens.
Initially, it was critical because this could be a user mistake in the platforms.yml.
Per example, %marenostrum5.type% = pjm"
We can just make this change for 4.1.12 and, in other versions ( if we don't have more time), add a new function ( for example, when checking the platform's connectivity) that checks if the command exists. 
So, if marenostrum5 is slurm, the commands of pjm wouldn't be found, raising a critical.
=> Change scheduler is not installed exception.

autosubmit/autosubmit.py, autosubmit/database/db_manager.py, autosubmit/job/job_list.py, autosubmit/job/job_list_persistence.py, autosubmit/job/job_package_persistence.py, autosubmit/job/job_utils.py, test/unit/test_checkpoints.py, test/unit/test_dependencies.py, test/unit/test_dic_jobs.py, test/unit/test_job_graph.py, test/unit/test_job_grouping.py, test/unit/test_job_package.py, test/unit/test_packages_persistence.py, test/unit/test_wrappers.py
Related to #1285 and PR #1914 
The idea of this PR is to include the code organization changes related to #1914. In this case:
* Adding the DbManager factory function
* Update JobListPersistenceDb and JobPackagePersistence `__init__` arguments
* Fix tests to mock the classes correctly changed above
These changes will make it easier to implement and review the changes needed to enable the support to Postgres.
=> Add DbManager factory function

.github/workflows/ci.yaml
Update to make the CI run unit, integration, and regression tests in parallel.
This PR supports #2241.
To avoid creating too many jobs, tests have been set to only Python 3.12 for integration and regression tests.
=> Update CI to parallel test execution

docker/README.md
Docker has a new backend, BuildKit, which improves build process but also avoids loading images built automatically into the local registry.
So you must remember to [use `docker build load`](https://docs.docker.com/reference/cli/docker/buildx/build/#load) so that the image is available in `docker images` or when you run it.
Also updated the container version in the docs, although we don't have to do that for every release, as the `Dockerfile` is parametrized.
=> Update Docker build instructions (load) and use 4.1.12

docker/README.md
There is a warning when following the README file of Docker:
```
[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
```
This is because when you run `docker run --init`, Docker will use `docker-init` as the init process instead of the one defined by the image, which in our case is `tini`. We don't have to use the `-init` flag to avoid that warning.
This is not critical since `docker-init` is backed up by `tini` but it is nice to not have this warning anymore.
=> Remove --init from docker README

autosubmit/platforms/slurmplatform.py
Import was deleted changed in the developing and improvement of maestro documentation this was creating an error where it was trying to suppress the file but the function wasn't being found
Closes #2289
=> maestro is failing due to deleted import

autosubmit/job/job.py, test/integration/test_run_command_integration.py, test/unit/test_job.py
Instead of getting the job start and finish timestamp from the timestamp files, Autosubmit was always using the fallback values.
~This was happening only when job.fail_count == 0~ 
EDIT: For retrials, it was looking at tmp folder instead of tmp/Log_$expid
Closes #2275
=> Timestamps fixes

autosubmit/autosubmit.py, autosubmit/database/db_common.py, autosubmit/experiment/detail_updater.py, test/unit/test_detail_updater.py
PR related to #2089
It makes `autosubmit expid` and `autosubmit delete` update the `details` table, which is used in the API.
This change, plus the one done in https://github.com/BSC-ES/autosubmit-api/issues/168 will keep the experiment detail data consistent.
=> Update details on expid/delete

autosubmit/helpers/processes.py, autosubmit/profiler/profiler.py, test/integration/test_run_command_integration.py, test/unit/helpers/test_processes.py
Closes #2314 
Suppresses the `psutil.ZombieProcess` in `autosubmit stop`. If we try to stop a process that's a zombie, there's not much we can do about it. It's not our responsibility to join/wait on it. There must be another part of the code that will do it, or the parent process will reap it -- trying to cull this process may result in other issues, and we would have to test that as well.
I'll trigger the builds a few times here before marking it ready for review. I've already done it locally.
=> Suppress psutil.ZombieProcess errors in autosubmit stop

autosubmit/platforms/slurmplatform.py
Basically, the X11 method is always called when it shouldn't.
closes https://github.com/BSC-ES/autosubmit/issues/2324
=> Revert a wrong change

pyproject.toml
Closes #2318 
See also: https://old.reddit.com/r/Python/comments/1jwbymm/psa_you_should_remove_wheel_from_your/ & https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#declaring-the-build-backend
=> Remove wheel from our build-system requires in pyproject.toml

CHANGELOG.md, autosubmit/platforms/platform.py, docs/source/userguide/configure/develop_a_project.rst, docs/source/userguide/configure/index.rst
**Check List**
Adds a log, and the other issue was a missing variable. 
This solves:
* a bug in the auth, derived from wrongly removing a as_conf parameter needed for the connect ( it doesn't send the full as_conf.experiment_data to save memory) 
* Now the log process is visible in the logs
```
-rwxrwxr-x 1 dbeltran dbeltran    0 May  5 10:21 20250505_102058_lumi_log_recovery_err.log*
drwxr-xr-x 2 dbeltran dbeltran 4.0K May  5 10:21 ./
-rwxrwxr-x 1 dbeltran dbeltran  200 May  5 10:21 20250505_102058_lumi_log_recovery.log*
```
=> Shared user fix and enable logs for log_process

.gitignore, .pylintrc, pyproject.toml
Creating files to standardize the vulture and pylint configurations
=> padronize vulture and pylint

test/unit/test_detail_updater.py
From https://github.com/BSC-ES/autosubmit/pull/2187/files#r2079053784
We have seen this test failing intermittently in the past few days. Saw this in the postgres branch too but wasn't sure if that was happening everytime/where.
**Check List**
=> Fix brittle test_details_updater (from Postgres branch)

autosubmit/job/job_list.py, test/unit/test_job_list.py
- Vulture not used variables fixed
=> job_list: Adjusting to remove unused variable

test/unit/test_diagram.py, test/unit/test_job_list.py
Create a test case for the function create_stats_report asserting if functions is creating files properly with the information from the jobs
=> Test create stats report

autosubmit/job/job.py
Class job -> there would be too many changes
- Vulture Fix
=> Job: second commit vulture fix

test/unit/test_expid.py
closes #2355
Test has a problem in which due to an expected failure it is taking 10+ seconds to be finished looking for a way to mitigate this time to reasonable execution time
=> Reduce the total running time of test_expid (~10s)

CHANGELOG.md, docker/demo/Dockerfile, docker/demo/entrypoint.sh
@kinow here is a tiny PR to install the API in a different environment than Autosubmit to prevent version conflicts because of the hard dependency the API now has with Autosubmit version 4.1.11
This should be enough to update our container with the latest version of both packages.
Note: I'm planning to release version 4.1.0 of the API, which will be a version before introducing Postgres. So, maybe I'll replace the default `AUTOSUBMIT_API_VERSION` later.
=> Update EDITO demo container to install API in different environment

docs/source/userguide/variables.rst
Closes #2123 
Numthreads was being referenced wrongly in the documentation, this is a fix to indicate to the user which one would be the correct directive to use
**Check List**
=> [Documentation] NUMTHREAD wrong use

autosubmit/autosubmit.py, autosubmit/history/utils.py, autosubmit/monitor/monitor.py
Closes #2364 
Two redundant functions were removed from the utils class
- create_path_if_not_exists
- create_path_if_not_exists_group_permission
Both function had as purpose to create the folder and add the proper permission, which could be done using Path()
**Check List**
=> [Refactoring] Redundant functions

CHANGELOG.md, CONTRIBUTING.md, autosubmit/autosubmit.py, autosubmit/git/autosubmit_git.py, docs/source/userguide/run/index.rst, test/conftest.py, test/integration/git/__init__.py, test/integration/git/test_autosubmit_git.py, test/integration/scripts/test_clean.py, test/integration/test_utils/git.py, test/unit/git/__init__.py, test/unit/git/test_autosubmit_git.py
Use cwd for subprocess calls, pass an array to subprocess calls, use as_conf instead of expdef_*, simplify logic by checking only for git changes (it includes submodules).
Closes #2446 
**Check List**
=> Fix git check for operational experiments

autosubmit/autosubmit.py, autosubmit/config/files/expdef-dummy.yml, test/integration/test_expid.py
Derived from #2187, I found that the delete was not safe and could result in the deletion of anything if it was directly called (without the command) 
This fixes it
**Check List**
=> Safe delete

MANIFEST.in
Hi @kinow, I created this PR because I think that during the installation the necessary yaml files that were being copied before the merge of the config parser are no longer present.
This was not noticeable in development environments, but, if you try to install as a library (as RtD was doing with @VindeeR ), it failed.
This was causing an issue with the `expid` command that was failing do to the lack of these files. I altered the `MANIFEST.in` file to include this folder. 
I tested with the immediate commit before the merge of the autosubmit config parser (1bed69), and it worked.
**Check List**
- [x ] I have read `CONTRIBUTING.md`.
- [x ] Contains logically grouped changes (else tidy your branch by rebase).
- [x ] Does not contain off-topic changes (use other PRs for other changes).
- [x …
=> add extra yaml files to be copyied by pip

CHANGELOG.md, autosubmit/autosubmit.py
Hi, @kinow ! 
Last week I bumped into this tiny error while trying to create an ro-crate.
The very helpful message with the placeholder ro-crate.yml file contained brackets, which, me as a user, I copied and pasted only to have a json error. (Actually, it was a bit more cryptic, but it does not matter).
After try-testing, I found that it was the double brackets. So I removed them.
Let me know if I am missing something.
**Check List**
=> Remove double brackets that create invalid json

CHANGELOG.md, autosubmit/autosubmit.py, test/integration/scripts/test_pklfix.py, test/integration/scripts/test_stop.py
Small PR to bypass confirmation prompts in `stop` and `pklfix` commands. Perfect to make it easier to integrate into users' automation scripts.
Based on what was missing for https://github.com/BSC-ES/autosubmit-api/pull/215
=> Force yes in command prompts

docs/source/userguide/create/index.rst
Fixes formatting inconsistencies in user guide for creating a new experiment.
Closes #2594
=> docs: fixes formatting for ini files in create-index
