SECURITY.md
autosubmit/autosubmit.py
autosubmit/job/job_dict.py
autosubmit/job/job_list.py
autosubmit/job/job_packages.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
autosubmit/platforms/slurmplatform.py
docs/source/userguide/configure/develop_a_project.rst
docs/source/userguide/manage/index.rst
test/regression/local_asparser_test.py
test/regression/local_asparser_test_4.1.py

Some of the logs or messages to the user had a couple of spelling mistakes to be fixed

Iss#1469 [QoL] - Adjusting logs flagged by IDE to be grammatically correct

---

autosubmit/autosubmit.py
autosubmit/database/db_common.py
autosubmit/database/db_structure.py
autosubmit/helpers/autosubmit_helper.py
autosubmit/helpers/utils.py
autosubmit/history/data_classes/job_data.py
autosubmit/history/database_managers/database_manager.py
autosubmit/history/experiment_status.py
autosubmit/job/job.py
autosubmit/job/job_common.py
autosubmit/job/job_dict.py
autosubmit/job/job_list.py
autosubmit/job/job_packages.py
autosubmit/job/job_utils.py
autosubmit/monitor/monitor.py
autosubmit/platforms/ecplatform.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/paramiko_submitter.py
autosubmit/platforms/pjmplatform.py
autosubmit/platforms/platform.py
autosubmit/platforms/psplatform.py
autosubmit/platforms/slurmplatform.py
autosubmit/statistics/utils.py
test/unit/test_history.py
test/unit/test_stop.py

Working on F841 where all the unused variables from a exception where eliminated focusing on a more manageable pull request

F841 part 1 - exception

---

autosubmit/autosubmit.py
autosubmit/job/job.py
autosubmit/job/job_list.py
autosubmit/job/job_packages.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
test/unit/provenance/test_rocrate.py
test/unit/test_database_managers.py
test/unit/test_dependencies.py
test/unit/test_describe.py
test/unit/test_dic_jobs.py
test/unit/test_history.py
test/unit/test_job_graph.py
test/unit/test_job_list.py
test/unit/test_run_command_intregation.py

Related to #1403 
commenting all the variable that were not used and had not being removed from the code

Iss#1403 fix f841 variables

---

test/unit/test_dependencies.py

As I was following the workflow of the test apply jobs edge, I notice a few of the functions being used were not full of coverage and trying to get a better understanding on how to properly create a test case for that function I've been working on the functions inside of it to expand the coverage and get more insight of the system

working on expanding the coverage of a pre existent test cehck_relationship

---

autosubmit/job/job_list.py
test/unit/test_job_list.py

Expanding coverage and adding return to the function

creating testing case for _normalize_to_filters function

---

autosubmit/job/job_list.py
test/unit/test_dependencies.py

As I was following the workflow of the test apply jobs edge, I notice a few of the functions being used were not full of coverage and trying to get a better understanding on how to properly create a test case for that function I've been working on the functions inside of it to expand the coverage and get more insight of the system

improving coverage of the test_check_chunk and adding appropriate return

---

autosubmit/job/job_list.py
test/unit/test_dependencies.py

As I was following the workflow of the test apply jobs edge, I notice a few of the functions being used were not full of coverage and trying to get a better understanding on how to properly create a test case for that function I've been working on the functions inside of it to expand the coverage and get more insight of the system

coverage improvment in function _check_dates

---

autosubmit/job/job_utils.py
test/unit/test_job_pytest.py

It was developed a couple extra targeting functions existent in the job/job_utils file focused on smoke test and making sure the objects works as intended

This commit is focused on improving coverage and basic tests

---

test/unit/test_run_command_intregation.py

This commit is merely focused on creating a wider coverage of a function already tested but with blind spots

creating function to test if profile is running correctly and generating the file

---

autosubmit/helpers/autosubmit_helper.py
test/unit/test_autosubmit_helper.py
test/unit/test_run_command_intregation.py

First commit of the file that targets the autosubmit_helper.py
This commit handles the handle_start_time function

Test autosubmit helper

---

autosubmit/monitor/diagram.py
test/unit/test_diagram.py

- Testing Class JobAggData
- File lint in accordance
- Refactoring code

creating test for the diagram.py + fix linting

---

autosubmit/helpers/autosubmit_helper.py
test/unit/test_autosubmit_helper.py

- Testing function get_allowed_members 
- File lint in accordance
- Refactoring code

test get_allowed_members in autosubmit_helper

---

autosubmit/monitor/diagram.py
test/unit/test_diagram.py

- Test function create_csv_stats
- Adding docstring to function

test for the function create_csv_stats in monitor/diagram.py

---

autosubmit/monitor/diagram.py
test/unit/test_diagram.py

- Testing Function create_bar_diagram
- File lint accordance
- Refactoring code

Test create bar diagram

---

autosubmit/monitor/diagram.py
test/unit/test_diagram.py

-Test function build_legends
-Adding docstring to function
-restructuring type hint

test for the function build_legends in monitor/diagram.py

---

autosubmit/autosubmit.py
autosubmit/job/job.py
autosubmit/job/job_dict.py
autosubmit/job/job_list.py
autosubmit/job/job_list_persistence.py
autosubmit/job/job_packager.py
autosubmit/job/job_packages.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
test/unit/conftest.py
test/unit/test_checkpoints.py
test/unit/test_dependencies.py
test/unit/test_dic_jobs.py
test/unit/test_expid_pytest.py
test/unit/test_job.py
test/unit/test_job_graph.py
test/unit/test_job_grouping.py
test/unit/test_job_list-pytest.py
test/unit/test_job_list.py
test/unit/test_job_package.py
test/unit/test_job_pytest.py
test/unit/test_log_recovery.py
test/unit/test_overwallclock.py
test/unit/test_stop.py
test/unit/test_wrappers.py
test/unit/test_wrappers_pytest.py

This PR almost fixes the memory leak; there is still some, but it is much less. 
Only fixed tests; did not add new ones due to lack of time.
This requires a new version in the autosubmit config parser. I'm working on the PR; I'll link the PR when I push it.

GH-2122-Mem-issues-more-leaks

---

autosubmit/statistics/utils.py

- Vulture not used function fixed

Statistics/Utils: Fixing code not used

---

autosubmit/statistics/utils.py

- Import order fixed
- Indentation fixed
- Type hint fixed
- Docstring Fixed

Statistics/Utils: Fixing linting of the file

---

autosubmit/autosubmit.py
autosubmit/database/db_common.py
autosubmit/experiment/experiment_common.py
docs/source/userguide/create/index.rst
docs/source/userguide/expids.rst
test/unit/test_expid.py
test/unit/test_expid_pytest.py
test/unit/utils/common.py

Add new type of experiment: evaluation
Closes #2194

Add expid evaluation option

---

autosubmit/history/database_managers/experiment_status_db_manager.py

- Import order fixed
- Indentation fixed
- Type hint fixed
- Docstring Fixed

status_db: Fixing indentation, lines too long, and import order

---

autosubmit/autosubmit.py

all tests were executed and approved
too many lint errors to adjust in a single commit

Autosubmit 100% trusted vulture

---

autosubmit/history/data_classes/job_data.py
autosubmit/history/database_managers/database_manager.py
autosubmit/history/database_managers/database_models.py
autosubmit/history/database_managers/experiment_history_db_manager.py
autosubmit/history/experiment_history.py
autosubmit/job/job.py
autosubmit/job/job_list.py
autosubmit/job/job_packages.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
autosubmit/platforms/slurmplatform.py
test/unit/test_job.py
test/unit/test_job_pytest.py
test/unit/test_paramiko_platform_pytest.py
test/unit/test_run_command_intregation.py
test/unit/test_slurm_platform_pytest.py

Closes #2179  
Needs: https://github.com/BSC-ES/autosubmit-config-parser/pull/74  #  Pending last review
Status: Working, some lines are not covered

Track the workflow commit

---

autosubmit/autosubmit.py
autosubmit/helpers/processes.py
autosubmit/helpers/utils.py
autosubmit/job/job_utils.py
test/unit/helpers/test_processes.py
test/unit/job/__init__.py
test/unit/job/test_job_utils.py
test/unit/test_run_command_intregation.py
test/unit/test_stop.py

Closes #2104 
The Autosubmit VM seems to be under heavy load, so I will refrain from doing the tests there for now.

Use psutil to retrieve the user experiments

---

autosubmit/autosubmit.py
autosubmit/scripts/autosubmit.py
log/log.py
test/unit/conftest.py
test/unit/scripts/__init__.py
test/unit/scripts/test_autosubmit.py

Fix exit code in autosubmit commands that return bool

---

docs/source/installation/index.rst

Specify python version and update command line

---

easybuild/recipes/autosubmit-4.X-dev-foss-2021b-Python-3.9.6.eb
easybuild/recipes/autosubmit-4.X-foss-2021b-Python-3.9.6.eb

This updates 4.1.12 and 4.1.13-dev recipes

update eb recipe

---

.github/workflows/ci.yaml

I noticed that PR #2241 was already merged to master when I merged PR #2255.
Now I'm recreating it to merge it into master directly.

Add parallel test execution

---

autosubmit/job/job_list.py

pylint was pointing some f-string lint error `C0209` in the job_list.py
Where strings where written `"{1}".format(var)` and were converted to `f"{var}"` allowing for a slimmer and more readable code

fixing f-string the error

---

autosubmit/autosubmit.py

Fixing linting issue C0209 where string uses formatting instead of f strings which is faster and more readable in the autosubmit.py
Where strings where written `"{1}".format(var)` and were converted to `f"{var}"` allowing for a slimmer and more readable code

fixing f-string error C0209 autosubmit.py

---

autosubmit/autosubmit.py
autosubmit/helpers/utils.py
test/unit/helpers/test_utils.py

Closes #2305 
Will check tomorrow if I can write a test for this, although this will be covered by the integration tests in another PR.
I'm just separating changes that are not part of Postgres from the Postgres branches (cc @LuiggiTenorioK who suggested this good idea!).

Add type to run_experiment, respect when users define AUTOSUBMIT_CONFIGURATION

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Add pull request and issue templates for GitHub

---

autosubmit/platforms/ecplatform.py
autosubmit/platforms/locplatform.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
autosubmit/platforms/sgeplatform.py

This fixes https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/issues/1035#note_360632
**Check List**
* ( User mapping, needs shared account ) 
* The calls touched require SSH tests

Fixed an Auth issue while using user_mapping

---

autosubmit/job/job.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
test/integration/test_run_command_integration.py
test/unit/platforms/__init__.py
test/unit/platforms/test_locplatform.py
test/unit/test_job.py

These are some changes to the timestamps of failed jobs which are not being correctly gathering. 
These will be included in the 4.1.14-release-branch
**Check List**
#2299

4.1.14 stat fixes

---

autosubmit/job/job.py
autosubmit/platforms/paramiko_platform.py
test/unit/test_platform.py

I'm planning on making 2 commits for this issue, one which includes the documentation of the wrapper, and one with the fix itself this way we can have the documentation in case something else pops up around the wrappers

first commit documenting the wrappers

---

autosubmit/history/database_managers/experiment_history_db_manager.py
autosubmit/history/experiment_history.py
autosubmit/job/job.py
autosubmit/platforms/platform.py
test/unit/test_job.py

**Check List**
I'll do it in another PR just to agilize this release. Manually tested
Already added from other fixes tries 
#2299

Fix database issues

---

autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/paramiko_submitter.py

- Cleaning code 
- More readable

Removing unused function from parent class

---

CHANGELOG.md
autosubmit/history/database_managers/experiment_history_db_manager.py
autosubmit/history/experiment_history.py
autosubmit/job/job.py
autosubmit/platforms/ecplatform.py
autosubmit/platforms/locplatform.py
autosubmit/platforms/paramiko_platform.py
autosubmit/platforms/platform.py
autosubmit/platforms/sgeplatform.py
docs/source/userguide/configure/develop_a_project.rst
docs/source/userguide/configure/index.rst
test/integration/test_run_command_integration.py
test/unit/platforms/__init__.py
test/unit/platforms/test_locplatform.py
test/unit/test_job.py
test/unit/test_platform.py

This branch is to write the changelog and do the release after the t-suite rans sucesfully with this version

4.1.14 release branch

---

autosubmit/platforms/ecplatform.py
autosubmit/platforms/locplatform.py
autosubmit/platforms/pbsplatform.py
autosubmit/platforms/pjmplatform.py
autosubmit/platforms/platform.py
autosubmit/platforms/psplatform.py
autosubmit/platforms/sgeplatform.py
autosubmit/platforms/slurmplatform.py
test/unit/platforms/__init__.py
test/unit/platforms/test_locplatform.py

Found while reviewing #2333 as the IDE spotted that function wasn't used anywhere else.
**Check List**

Remove unused function jobs_in_queue, add small unrelated test

---

test/conftest.py
test/unit/test_diagram.py
test/unit/test_statistics.py

- test for the function_seq, populate_statistics in diagram

diagram seq and populate_statistics test

---

autosubmit/autosubmit.py
autosubmit/helpers/autosubmit_helper.py
test/integration/test_log_recovery.py
test/unit/test_autosubmit_helper.py

- Testing function handle_start_after
- File lint in accordance
- Refactoring code

test handle_start_after and refactoring code

---

autosubmit/autosubmit.py
test/integration/test_expid.py
test/unit/test_autosubmit_git.py
test/unit/test_expid.py

refactoring existent code for expid where it is used the path library and a new unit test code was generate to make sure everything works as expected

Expid refactoring and development of a testing function

---

.pylintrc
autosubmit/autosubmit.py
test/unit/test_autosubmit.py

It was updated how to create a path, passing a value Path as the variable.
It was created a unit test for the function copy_as_config validating if the copy and creation of the files were done properly

Iss#2085 Validating Path generation

---

README.md

Remove Codacy badge from readme

---

CHANGELOG.md
autosubmit/autosubmit.py
autosubmit/statistics/jobs_stat.py
autosubmit/statistics/utils.py
docs/source/userguide/monitor_and_check/index.rst
test/unit/statistics/test_utils.py

Closes #2254  
Closes #1473 
**Check List**

[stats][ro-crate] Prevent zero division error, and trying to iterate a none

---

CHANGELOG.md
autosubmit/autosubmit.py
test/integration/test_describe.py

Accept the ERROR log level in the command line

---

.github/workflows/ci.yaml
.github/workflows/codeql.yml
.github/workflows/docker.yaml
CHANGELOG.md
docker/Dockerfile

Closes #2359
Had some minutes today before going home, so wrote a quick fix for #2359, and then added some code to see if we can build with docker and run some basic docker tests.
**Check List**

Add $USER variable to our Docker container, and test it in GH Actions

---

CHANGELOG.md

Related to #2446 
**Check List**

Correct the 4.1.14 and 4.1.15 changelogs

---

CONTRIBUTING.md

Closes #2444 
Creating instructions on how to run the slurm-container locally so tests can be executed
**Check List**

[Documentation] CONTRIBUTING.md run Slurm

---

autosubmit/autosubmit.py
autosubmit/job/job_utils.py

Closes #2441
Closes #2136 
As I was creating tests and investigating the Slurm platform I run into some unused or bad code.
**Check List**

Getting rid of unused code, and doing some cleaning

---

autosubmit/platforms/paramiko_platform.py
test/integration/conftest.py
test/integration/test_mail.py
test/integration/test_paramiko_platform.py
test/integration/test_utils/__init__.py
test/integration/test_utils/networking.py

Fix flaky tests, use system ephemeral ports instead of fixed ranges for networking ports

---

autosubmit/autosubmit.py
autosubmit/config/configcommon.py
autosubmit/helpers/autosubmit_helper.py
autosubmit/helpers/processes.py
autosubmit/helpers/utils.py
test/integration/helpers/__init__.py
test/integration/helpers/test_utils.py
test/unit/config/test_load_workflow_commit.py
test/unit/helpers/test_processes.py
test/unit/test_autosubmit_helper.py
test/unit/test_job.py

Had some minutes in the afternoon today but not enough to start working on #2474, so picked an item from my list, and wrote test for `NaturalSort`. Noticed the other functions in the helpers were missing tests too, so added some new ones here.
**Check List**

Adding unit tests for autosubmit.helpers

---

autosubmit/provenance/rocrate.py
test/unit/provenance/test_rocrate.py

From: https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/merge_requests/475#note_386025
Was testing an issue with RO-Crates from @apuiggro, and noticed some IDE warnings, so I spent 5 mins reviewing them after I finished with that issue, and produced this PR :+1: 
**Check List**

Fix linter and mypy issues in provenance.py

---

CHANGELOG.md
autosubmit/config/configcommon.py
test/conftest.py
test/unit/test_autosubmit.py

improving the message error that happened whenever the directive FOR was used with wrong identation
Closes #2488 
**Check List**

[Improvement] Improve 'FOR' error message

---

.coveragerc

Ignore pass statements in coverage reports

---

.coveragerc

Reverts #2578 
Sorry! :bow: 
**Check List**

[coverage] Ignore pass using a regex
